"""Initial clea

Revision ID: 6d3fdf5e6e62
Revises: 
Create Date: 2026-05-24 13:04:48.875437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d3fdf5e6e62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'signed_at')
    op.drop_column('contracts', 'notes')
    op.drop_column('properties', 'deposit_amount')
    op.drop_column('properties', 'year_built')
    op.drop_column('properties', 'floor')
    op.drop_column('properties', 'image_url')
    op.drop_column('properties', 'total_floors')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.add_column('properties', sa.Column('total_floors', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('year_built', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('deposit_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('signed_at', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
