"""add full_name to users

Revision ID: ef8676da9899
Revises: 111sql111
Create Date: 2026-05-22 11:16:04.580707

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ef8676da9899"
down_revision: Union[str, Sequence[str], None] = "111sql111"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contracts", sa.Column("monthly_payment", sa.Float(), nullable=True))
    op.add_column("contracts", sa.Column("contract_number", sa.String(), nullable=True))
    op.add_column("contracts", sa.Column("signed_at", sa.Date(), nullable=True))
    op.add_column("contracts", sa.Column("notes", sa.Text(), nullable=True))
    op.create_unique_constraint(None, "contracts", ["contract_number"])
    op.add_column("properties", sa.Column("property_type", sa.String(), nullable=True))
    op.add_column("properties", sa.Column("area", sa.Float(), nullable=True))
    op.add_column("properties", sa.Column("rooms_count", sa.Integer(), nullable=True))
    op.add_column("properties", sa.Column("floor", sa.Integer(), nullable=True))
    op.add_column("properties", sa.Column("total_floors", sa.Integer(), nullable=True))
    op.add_column("properties", sa.Column("year_built", sa.Integer(), nullable=True))
    op.add_column("properties", sa.Column("deposit_amount", sa.Float(), nullable=True))
    op.add_column("properties", sa.Column("image_url", sa.String(), nullable=True))
    op.alter_column(
        "properties",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.add_column("tenants", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column(
        "tenants", sa.Column("registration_address", sa.String(), nullable=True)
    )
    op.add_column("tenants", sa.Column("email", sa.String(), nullable=True))
    op.add_column("tenants", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("full_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_column("users", "is_active")
    op.drop_column("users", "full_name")
    op.drop_column("tenants", "notes")
    op.drop_column("tenants", "email")
    op.drop_column("tenants", "registration_address")
    op.drop_column("tenants", "birth_date")
    op.alter_column(
        "properties",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("properties", "image_url")
    op.drop_column("properties", "deposit_amount")
    op.drop_column("properties", "year_built")
    op.drop_column("properties", "total_floors")
    op.drop_column("properties", "floor")
    op.drop_column("properties", "rooms_count")
    op.drop_column("properties", "area")
    op.drop_column("properties", "property_type")
    op.drop_constraint(None, "contracts", type_="unique")
    op.drop_column("contracts", "notes")
    op.drop_column("contracts", "signed_at")
    op.drop_column("contracts", "contract_number")
    op.drop_column("contracts", "monthly_payment")
    # ### end Alembic commands ###
